### ISSUE TITLE
Broken App with outdated packages

### ISSUE THREAD

**Issue by pranav-bhatt** [dscpesu/DSC-PESU#11]
So I've been trying for the last 12 hours to get the app working. It seems to be some issue with sass-loader where @material/elevation/mixin is not being able to be read. 

```
./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/App.scss)

SassError: File to import not found or unreadable: @material/elevation/mixins.
        on line 23 of node_modules/@material/button/_mixins.scss
        from line 23 of node_modules/@material/button/mdc-button.scss
        from line 23 of node_modules/@material/react-button/index.scss
        from line 14 of /home/pranav/Desktop/DSC-PESU/src/App.scss

 import "@material/elevation/mixins";
```
There was some other error I got when i tried to start the project directly from a fresh clone from the repo.

```
./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/App.scss)
@import "@material/button/mdc-button";
^
      File to import not found or unreadable: @material/button/mdc-button.
      in /home/pranav/Desktop/DSC-PESU/node_modules/@material/react-button/index.scss (line 23, column 1)
```

I haven't been able to figure out how to solve it. Any input will be appreciated!

**Comment by varungupta3009** [comment]
That's not an issue with the project. Did you make sure to set the `SASS_PATH` in the environment? It looks like you haven't set it. It is one of the requirements as mentioned in https://github.com/material-components/material-components-web-react. I thought I had included it in `./start.bat`. Check once and let me know.

**Comment by pranav-bhatt** [comment]
Yeah I figured it out after painstakingly backtracking 😓. Sorry for not updating sooner!

**Comment by varungupta3009** [comment]
Yeah no issues.
