### ISSUE TITLE
bug: Broken link

### ISSUE THREAD

**Issue by aravindvnair99** [dscpesu/DSC-PESU#12]
LinkedIn link for Richa is invalid.

Currently is: https://dscpesu.github.io/DSC-PESU/#/team

Should be: https://linkedin.com/in/richaaaa

**Comment by varungupta3009** [comment]
Yup. I didn't have the link. Pushing :)

**Comment by aravindvnair99** [comment]
@varungupta3009 You forget the hash. Check here: https://github.com/dscpesu/DSC-PESU/commit/de3533fb832991c6932bbccabfda962f916d737a#r39530426

**Comment by varungupta3009** [comment]
That's so weird. Prettier is adding a hash while saving... Amended.
