### ISSUE TITLE
Navbar links won't work

### ISSUE THREAD

**Issue by aashutoshrathi** [dscpesu/DSC-PESU#3]
No link in Navbar works except Project.

**Comment by varungupta3009** [comment]
Hey @aashutoshrathi, so the GitHub pages version is for basic preview only, I used routes, and gh-pages doesn't support routing, so I had to use the Hash Router to make it work. Anyway, I migrated everything to Browser Router and as soon as our server is up, the final website will be available at https://dsc.pes.edu. Thanks for helping :)
