### ISSUE TITLE
Sustainable hosting 

### ISSUE THREAD

**Issue by ghost** [dscpesu/DSC-PESU#4]
We are planning to shift to a sustainable hosting provider for our web-app. The current web server seems to go down when usage is less (I guess that's an efficient method), but we would like to migrate to a professional web service provider. 

Discussions/suggesions are welcome :slightly_smiling_face:

**Comment by pranav-bhatt** [comment]
can we just create a github pages and deploy to that directly?

**Comment by varungupta3009** [comment]
The main problem here is dynamic hosting. The GH Pages site is already up at https://dscpesu.github.io/DSC-PESU/ but React Router doesn't work very well with static hosting on GH Pages. Other static hosts could fix the issue but then we come to problems like #6, #7, #8, and #10 that all need a server to run. Currently, all we can work on is cosmetic changes, but to add true functionality, we need a better host.

The root of the problem, though, is PESU and its servers. We could easily use Heroku for hosting a dynamic ready site but PESU isn't providing the domain separately from their AWS servers...

**Comment by pranav-bhatt** [comment]
What about Firebase hosting? we are limited to 1GB, but its completely free AFAIK.

**Comment by varungupta3009** [comment]
Yup, Firebase or Heroku is fine, but we still need a domain.

@UmashankarTriforce Did they reply? Those emails you sent way back in September requesting the domain XD

**Comment by pranav-bhatt** [comment]
We can easily update the domain later IG, so I'll set up a firebase site for now, just so we can continue development. Would you mind messaging me the DSC Google account credentials on WhatsApp so I can set it up?

**Comment by varungupta3009** [comment]
> Would you mind messaging me the DSC Google account credentials on WhatsApp so I can set it up?

Unfortunately, I don't have it too. @UmashankarTriforce do you mind DMing him the details? I'll ask @techgod too...

**Comment by ghost** [comment]
@varungupta3009 About the previous comment, I did send them an email a few months back, but to get no response from them. So I guess we can leave that out for an option. 
Also I don't have the G creds for DSC so @techgod should have it. 

@pranav-bhatt You might want to put the backend work on hold atm. Our first priority is to make sure we have a good and reliable host for frontend. From what I gather, GH Pages do not render well with static react, so you might wanna find out alternatives for this. Leave the domain name aside, we can take it up later. 

Once we have our host for frontend ready without any compromises, we'll look into backend service. What do you say @varungupta3009 ?

**Comment by pranav-bhatt** [comment]
> @varungupta3009 About the previous comment, I did send them an email a few months back, but to get no response from them. So I guess we can leave that out for an option.
> Also I don't have the G creds for DSC so @techgod should have it.
> 
> @pranav-bhatt You might want to put the backend work on hold atm. Our first priority is to make sure we have a good and reliable host for frontend. From what I gather, GH Pages do not render well with static react, so you might wanna find out alternatives for this. Leave the domain name aside, we can take it up later.
> 
> Once we have our host for frontend ready without any compromises, we'll look into backend service. What do you say @varungupta3009 ?

Right so I was talking about using the DSC-PESU account to host the site on firebase, and that's why I was asking for the credentials :)

**Comment by varungupta3009** [comment]
> > @varungupta3009 About the previous comment, I did send them an email a few months back, but to get no response from them. So I guess we can leave that out for an option.
> > Also I don't have the G creds for DSC so @techgod should have it.
> > 
> > @pranav-bhatt You might want to put the backend work on hold atm. Our first priority is to make sure we have a good and reliable host for frontend. From what I gather, GH Pages do not render well with static react, so you might wanna find out alternatives for this. Leave the domain name aside, we can take it up later.
> > 
> > Once we have our host for frontend ready without any compromises, we'll look into backend service. What do you say @varungupta3009 ?
> 
> Right so I was talking about using the DSC-PESU account to host the site on firebase, and that's why I was asking for the credentials :)

Yup. For now, let's keep the FE as the first priority. @UmashankarTriforce but if your BE is ready, you can start integrating it too.

@pranav-bhatt So @techgod will be online soon and he'll give you the creds. Till then you can start configuring Firebase on the project. Also gonna switch to TypeScript soon so that the project is a bit more future ready and stable.

**Comment by pranav-bhatt** [comment]
Ok so im opening another issue and I think that needs to be dealt with first

**Comment by pranav-bhatt** [comment]
Alright! Finished hosting it on firebase: https://dsc-pes.web.app.

I'm closing this issue. Do open again in case you would like to discuss further!
